name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package would this feature affect?
      options:
        - Backend (API)
        - Mobile (React Native)
        - Web (Dashboard)
        - Multiple Packages
        - New Package
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Scheduling & Shifts
        - Shift Pool & Claims
        - Swaps & Trades
        - Ghost Kitchen
        - Network & Multi-Restaurant
        - Notifications
        - Analytics & Reporting
        - Authentication & Identity
        - Payments & Payroll
        - UI/UX Improvement
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a [restaurant manager/worker], I want to [do something] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Other approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or links to similar features
      placeholder: Drag and drop images or paste links
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
